# Generated by Django 5.2.1 on 2025-08-05 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_echeance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True)),
                ('quantite', models.IntegerField()),
                ('pays_origine', models.CharField(max_length=100)),
                ('region_actuelle', models.CharField(max_length=100)),
                ('lieu_actuel', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_transit', 'En transit'), ('douane', 'Douane'), ('livre', 'Livré'), ('bloque', 'Bloqué')], default='en_transit', max_length=20)),
                ('date_expedition', models.DateField()),
                ('date_livraison_prevue', models.DateField()),
                ('transporteur', models.CharField(max_length=100)),
                ('numero_suivi', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Import/Transit',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EtapeTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('statut', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('import_transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='fournisseurs.importtransit')),
            ],
            options={
                'verbose_name_plural': 'Étapes de transit',
                'ordering': ['ordre', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('fin_de_vie', 'Fin de vie')], default='actif', max_length=20)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('date_livraison', models.DateField()),
                ('statut', models.CharField(choices=[('a_livrer', 'À livrer'), ('en_cours', 'En cours'), ('livree', 'Livrée')], default='a_livrer', max_length=20)),
                ('bon_livraison_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('livreur', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit')),
            ],
            options={
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='importtransit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit'),
        ),
        migrations.CreateModel(
            name='CommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_commande', models.DateField()),
                ('date_livraison_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit')),
            ],
            options={
                'verbose_name_plural': "Commandes d'achat",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('a_envoyer', 'À envoyer'), ('envoyee', 'Envoyée'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='a_envoyer', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit')),
            ],
            options={
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-date_creation'],
            },
        ),
    ]
