# Generated by Django 5.2.1 on 2025-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_importtransit_etapetransit_produit_livraison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Saisons',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='saisons',
            field=models.ManyToManyField(blank=True, related_name='produits', to='fournisseurs.saison'),
        ),
    ]
