# Generated by Django 5.2.1 on 2025-08-09 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0005_default_saisons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='id_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_boncommande_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='id_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_commandeachat_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='echeance',
            name='id_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_echeance_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='id_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_fournisseur_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importtransit',
            name='id_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_importtransit_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraison',
            name='id_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_livraison_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='id_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_produit_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saison',
            name='id_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
