# Generated by Django 5.2.5 on 2025-08-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0006_boncommande_id_tenant_commandeachat_id_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommande',
            name='id_tenant',
        ),
        migrations.RemoveField(
            model_name='commandeachat',
            name='id_tenant',
        ),
        migrations.RemoveField(
            model_name='echeance',
            name='id_tenant',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='id_tenant',
        ),
        migrations.RemoveField(
            model_name='importtransit',
            name='id_tenant',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='id_tenant',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='id_tenant',
        ),
        migrations.RemoveField(
            model_name='saison',
            name='id_tenant',
        ),
    ]
