# Generated by Django 5.2.1 on 2025-08-14 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0007_remove_boncommande_id_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etapetransit',
            name='date_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapetransit',
            name='date_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapetransit',
            name='duree_estimee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etapetransit',
            name='nom',
            field=models.CharField(default='Étape', max_length=255),
        ),
        migrations.AddField(
            model_name='etapetransit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapetransit',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importtransit',
            name='date_arrivee_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importtransit',
            name='nombre_conteneurs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='importtransit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importtransit',
            name='poids_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='importtransit',
            name='port_arrivee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importtransit',
            name='port_depart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importtransit',
            name='valeur_totale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='etapetransit',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('retardee', 'Retardée')], default='en_attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importtransit',
            name='statut',
            field=models.CharField(choices=[('en_preparation', 'En préparation'), ('en_transit', 'En transit'), ('douane', 'Douane'), ('arrive', 'Arrivé'), ('en_stock', 'En stock'), ('livre', 'Livré'), ('bloque', 'Bloqué')], default='en_preparation', max_length=20),
        ),
        migrations.CreateModel(
            name='TrajetProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('statut_global', models.CharField(choices=[('en_preparation', 'En préparation'), ('en_transit', 'En transit'), ('arrive', 'Arrivé'), ('en_stock', 'En stock'), ('en_livraison', 'En livraison'), ('livre', 'Livré')], default='en_preparation', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
                ('import_transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_produits', to='fournisseurs.importtransit')),
                ('livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trajets_produits', to='fournisseurs.livraison')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trajets des produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EtapeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Étape de livraison', max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('date_prevue', models.DateField()),
                ('date_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('retardee', 'Retardée')], default='en_attente', max_length=50)),
                ('description', models.TextField()),
                ('livreur', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('trajet_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_livraison', to='fournisseurs.trajetproduit')),
            ],
            options={
                'verbose_name_plural': 'Étapes de livraison',
                'ordering': ['ordre', 'date_prevue'],
            },
        ),
    ]
