# Generated by Django 5.2.1 on 2025-08-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0008_etapetransit_date_prevue_etapetransit_date_reelle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajetproduit',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='trajetproduit',
            name='import_transit',
        ),
        migrations.RemoveField(
            model_name='trajetproduit',
            name='livraison',
        ),
        migrations.RemoveField(
            model_name='trajetproduit',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='trajetproduit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='etapetransit',
            name='date_prevue',
        ),
        migrations.RemoveField(
            model_name='etapetransit',
            name='date_reelle',
        ),
        migrations.RemoveField(
            model_name='etapetransit',
            name='duree_estimee',
        ),
        migrations.RemoveField(
            model_name='etapetransit',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='etapetransit',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='etapetransit',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='importtransit',
            name='date_arrivee_reelle',
        ),
        migrations.RemoveField(
            model_name='importtransit',
            name='nombre_conteneurs',
        ),
        migrations.RemoveField(
            model_name='importtransit',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='importtransit',
            name='poids_total',
        ),
        migrations.RemoveField(
            model_name='importtransit',
            name='port_arrivee',
        ),
        migrations.RemoveField(
            model_name='importtransit',
            name='port_depart',
        ),
        migrations.RemoveField(
            model_name='importtransit',
            name='valeur_totale',
        ),
        migrations.AddField(
            model_name='livraison',
            name='niveau',
            field=models.CharField(choices=[('en_transit', 'En transit'), ('en_douane', 'En douane'), ('livree', 'Livrée')], default='en_transit', max_length=20),
        ),
        migrations.AlterField(
            model_name='etapetransit',
            name='statut',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='importtransit',
            name='statut',
            field=models.CharField(choices=[('en_transit', 'En transit'), ('douane', 'Douane'), ('livre', 'Livré'), ('bloque', 'Bloqué')], default='en_transit', max_length=20),
        ),
        migrations.DeleteModel(
            name='EtapeLivraison',
        ),
        migrations.DeleteModel(
            name='TrajetProduit',
        ),
    ]
