# Generated by Django 4.2.7 on 2024-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0009_remove_trajetproduit_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='niveau',
            field=models.CharField(
                choices=[
                    ('en_transit', 'En transit'),
                    ('en_douane', 'En douane'),
                    ('livree', 'Livrée')
                ],
                default='en_transit',
                max_length=20
            ),
        ),
    ]
