# Generated by Django 5.2.1 on 2025-08-14 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0010_add_niveau_to_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=255)),
                ('date_passage', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('retarde', 'Retardé')], default='en_cours', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('import_transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_lieux', to='fournisseurs.importtransit')),
            ],
            options={
                'verbose_name_plural': 'Historique des lieux',
                'ordering': ['ordre', 'date_passage'],
            },
        ),
    ]
