# Generated by Django 5.2.1 on 2025-08-15 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0011_historiquelieu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commandeachat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='echeance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='user',
        ),
        migrations.RemoveField(
            model_name='importtransit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='user',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='user',
        ),
        migrations.AddField(
            model_name='boncommande',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='fournisseurs.tenant'),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_achat', to='fournisseurs.tenant'),
        ),
        migrations.AddField(
            model_name='echeance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='fournisseurs.tenant'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='fournisseurs.tenant'),
        ),
        migrations.AddField(
            model_name='importtransit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imports_transit', to='fournisseurs.tenant'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='fournisseurs.tenant'),
        ),
        migrations.AddField(
            model_name='produit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='fournisseurs.tenant'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='fournisseurs.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
