# Generated by Django 5.2.1 on 2025-08-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0012_tenant_remove_boncommande_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name']},
        ),
    ]
